name: bulding blocks
on: push
jobs:
  echo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a message
        run: echo "Building blocks workflow executed successfully!"
  echo-job2:
    runs-on: ubuntu-latest
    steps:
      - name: failed job
        run: |
          echo "This job is designed to fail."
          exit 1
      - name: goodbye
        run: echo "Goodbye!"
  echo-job3:
    runs-on: ubuntu-latest
    steps:
      - name: Successfull job
        run: |
          echo "This job is designed to fail."
          exit 0
      - name: goodbye
        run: echo "Goodbye!"
